---
ID: "352df5d5-6ed5-8e49-82a8-12716cafd370"
Parent: "ffc03e83-a7a8-12f8-1be5-49eb6444fd9d"
Template: "ab86861a-6030-46c5-b394-e8f99e8b87db"
Path: /sitecore/templates/Commerce/Catalog Generated/Components/ConnectSellableItem/TrainingSellableItemToSellableItem
DB: master
Languages:
- Language: en
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: TrainingSellableItemToSellableItem
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200321T180648Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Anonymous
